version: '3'
services:
  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thestocker
    ports:
      - 3306:3306
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/thestocker?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone